"use client"

import { TrendingUp } from "lucide-react"
import { Area, AreaChart, CartesianGrid, XAxis, YAxis } from "recharts"

import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card"
import {
    ChartContainer,
    ChartTooltip,
    ChartTooltipContent,
} from "@/components/ui/chart"

export const description = "Revenue area chart (12 months)"

// Dummy revenue data for last 12 months
const chartData = [
    { month: "January", revenue: 2500 },
    { month: "February", revenue: 4800 },
    { month: "March", revenue: 3100 },
    { month: "April", revenue: 6000 },
    { month: "May", revenue: 4200 },
    { month: "June", revenue: 7500 },
    { month: "July", revenue: 5000 },
    { month: "August", revenue: 8900 },
    { month: "September", revenue: 4700 },
    { month: "October", revenue: 9200 },
    { month: "November", revenue: 6100 },
    { month: "December", revenue: 11000 },
]

const chartConfig = {
    revenue: {
        label: "Revenue",
        color: "var(--chart-3)",
    },
}

export default function RevenueAreaChart() {
    return (
        <Card>
            <CardHeader>
                <CardTitle>Revenue from Course Sales</CardTitle>
                <CardDescription>
                    Monthly revenue generated by students purchasing courses (last 12 months)
                </CardDescription>
            </CardHeader>
            <CardContent>
                <ChartContainer config={chartConfig} className={"h-[300px] w-full"}>
                    <AreaChart
                        accessibilityLayer
                        data={chartData}
                        margin={{
                            left: 12,
                            right: 12,
                        }}
                    >
                        <CartesianGrid vertical={false} />
                        <XAxis
                            dataKey="month"
                            tickLine={false}
                            axisLine={false}
                            tickMargin={8}
                            tickFormatter={(value) => value.slice(0, 3)} // "Jan", "Feb"
                        />
                        <YAxis
                            tickFormatter={(value) => `$${value / 1000}k`} // Format like $2.5k
                            axisLine={false}
                            tickLine={false}
                        />
                        <ChartTooltip
                            cursor={false}
                            content={<ChartTooltipContent indicator="line" />}
                        />
                        <Area
                            dataKey="revenue"
                            type="linear" // <- sharp changes instead of smooth "natural"
                            fill="var(--color-revenue)"
                            fillOpacity={0.4}
                            stroke="var(--color-revenue)"
                            strokeWidth={2}
                        />
                    </AreaChart>
                </ChartContainer>
            </CardContent>
            <CardFooter>
                <div className="flex w-full items-start gap-2 text-sm">
                    <div className="grid gap-2">
                        <div className="flex items-center gap-2 leading-none font-medium">
                            Revenue grew by 25.7% compared to last year{" "}
                            <TrendingUp className="h-4 w-4" />
                        </div>
                        <div className="text-muted-foreground flex items-center gap-2 leading-none">
                            January - December 2024
                        </div>
                    </div>
                </div>
            </CardFooter>
        </Card>
    )
}
